### PR TITLE
Updates for Hello Vectors

### PR DESCRIPTION
**Pull request by jwmsft**
Add license notice, formatting and general cleanup

### CODE REVIEW

**Comment by clarkezone** [comment]
Can this be merged yet?

**Comment by ajbennet** [comment]
> Can this be merged yet?
We still need Scott to add the new nuget for WinUI. But I guess, we ll ask him to do that in a separate PR.

**Comment by jwmsft** [comment]
This PR was closed, but not merged, so the changes aren't in the 'develop' branch yet. It needs to be merged.

**Comment by ajbennet** [comment]
> This PR was closed, but not merged, so the changes aren't in the 'develop' branch yet. It needs to be merged.

My bad. Merged it now.

**Pull request merged**
